# fly.toml app configuration file generated for ecf-restaurant-laurent-kujawa on 2023-05-22T16:01:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ecf-restaurant-laurent-kujawa"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
